PROJECT := test
GNUCC   :=
DEFS    :=
INCS    := include
SRCS    := src/main.c
LIBS    :=
SCRIPT  :=
COMMON  := common

#----------------------------------------------------------#
include $(COMMON)/intros/make/stm32f0discovery/makefile.iarcc
#----------------------------------------------------------#

include $(COMMON)/cmsis/makefile
include $(COMMON)/device/makefile
include $(COMMON)/startup/makefile
include $(COMMON)/intros/makefile

#----------------------------------------------------------#
include $(COMMON)/make/makefile
#----------------------------------------------------------#
